vim.pack.add({
	{ src = "https://github.com/neovim/nvim-lspconfig" },
})

vim.lsp.enable("biome")
vim.lsp.enable("clangd")
vim.lsp.enable("cssls")
vim.lsp.enable("gopls")
vim.lsp.enable("html")
vim.lsp.enable("jsonls")
vim.lsp.enable("lua_ls")
vim.lsp.enable("pyright")
vim.lsp.enable("svelte")
vim.lsp.enable("tailwindcss")
vim.lsp.enable("ts_ls")
vim.lsp.enable("sqls")
vim.lsp.enable("jdtls")
vim.lsp.enable("ols")

vim.keymap.set("n", "K", vim.lsp.buf.hover)
vim.keymap.set("n", "J", vim.diagnostic.open_float)
vim.keymap.set("n", "R", vim.lsp.buf.rename)
vim.keymap.set("n", "]g", vim.diagnostic.get_next, { desc = "Next Diagnostic" })
vim.keymap.set("n", "[g", vim.diagnostic.get_prev, { desc = "Prev Diagnostic" })
vim.keymap.set({ "n", "v" }, "<leader>c", vim.lsp.buf.code_action, { desc = "Code Action" })
