vim.lsp.enable("lua_ls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("biome")
vim.lsp.enable("gopls")

vim.keymap.set('n', 'K', vim.lsp.buf.hover)
vim.keymap.set('n', 'J', vim.diagnostic.open_float)
vim.keymap.set('n', 'R', vim.lsp.buf.rename)
vim.keymap.set('n', ']g', vim.diagnostic.get_next, { desc = "Next Diagnostic" })
vim.keymap.set('n', '[g', vim.diagnostic.get_prev, { desc = "Prev Diagnostic" })
